name: argocds-redis-v7.0.8-alpine
on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/argocds-redis-v7.0.8-alpine.yml'       

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2            

      - name: Login in ALIYUN Registry
        uses: docker/login-action@v1
        with:
          registry: registry-intl.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUNHUB_USERNAME }}
          password: ${{ secrets.ALIYUNHUB_TOKEN }}

      - name: Build and push
        run: |
          docker pull ccr.ccs.tencentyun.com/argocds/redis:7.0.8-alpine
          docker tag ccr.ccs.tencentyun.com/argocds/redis:7.0.8-alpine registry-intl.cn-hangzhou.aliyuncs.com/deveops_argocds/redis:7.0.8-alpine
          docker push registry-intl.cn-hangzhou.aliyuncs.com/deveops_argocds/redis:7.0.8-alpine