name: checkmarx_2ms-latest
on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/checkmarx_2ms-latest.yml'       

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2            

      - name: Login in ALIYUN Registry
        uses: docker/login-action@v1
        with:
          registry: registry-intl.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUNHUB_USERNAME }}
          password: ${{ secrets.ALIYUNHUB_TOKEN }}

      - name: Build and push
        run: |
          docker pull checkmarx/2ms:latest
          docker tag checkmarx/2ms:latest registry-intl.cn-hangzhou.aliyuncs.com/fky357/checkmarx/2ms:latest
          docker push registry-intl.cn-hangzhou.aliyuncs.com/fky357/checkmarx/2ms:latest
