name: dongtai-logstash-v1.15.0
on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/dongtai-logstash-v1.15.0.yml'       

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2            

      - name: Login in ALIYUN Registry
        uses: docker/login-action@v1
        with:
          registry: registry-intl.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUNHUB_USERNAME }}
          password: ${{ secrets.ALIYUNHUB_TOKEN }}

      - name: Build and push
        run: |
          docker pull registry.cn-beijing.aliyuncs.com/huoxian_pub/dongtai-logstash:1.16.0
          docker tag registry.cn-beijing.aliyuncs.com/huoxian_pub/dongtai-logstash:1.16.0 registry-intl.cn-hangzhou.aliyuncs.com/fky357/dongtai-logstash:1.16.0
          docker push registry-intl.cn-hangzhou.aliyuncs.com/fky357/dongtai-logstash:1.16.0
