name: flannel-cni-plugin-v1.1.0
on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/flannel-cni-plugin-v1.1.0.yml'       
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2            

      - name: Login in ALIYUN Registry
        uses: docker/login-action@v1
        with:
          registry: registry-intl.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUNHUB_USERNAME }}
          password: ${{ secrets.ALIYUNHUB_TOKEN }}

      - name: Build and push
        run: |
          docker pull docker.io/flannel/flannel-cni-plugin:v1.1.0
          docker tag docker.io/flannel/flannel-cni-plugin:v1.1.0 registry-intl.cn-hangzhou.aliyuncs.com/deveops_k8s/flannel-cni-plugin:v1.1.0
          docker push registry-intl.cn-hangzhou.aliyuncs.com/deveops_k8s/flannel-cni-plugin:v1.1.0
