name: flannel-v0.20.1
on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/flannel-v0.20.1.yml'       

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2            

      - name: Login in ALIYUN Registry
        uses: docker/login-action@v1
        with:
          registry: registry-intl.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUNHUB_USERNAME }}
          password: ${{ secrets.ALIYUNHUB_TOKEN }}

      - name: Build and push
        run: |
          docker pull quay.io/coreos/flannel:v0.20.1
          docker tag quay.io/coreos/flannel:v0.20.1 registry-intl.cn-hangzhou.aliyuncs.com/deveops_k8s/flannel:v0.20.1
          docker push registry-intl.cn-hangzhou.aliyuncs.com/deveops_k8s/flannel:v0.20.1
