name: jessie-dnsutils-v1.3
on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/jessie-dnsutils-v1.3.yml'       

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2            

      - name: Login in ALIYUN Registry
        uses: docker/login-action@v1
        with:
          registry: registry-intl.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUNHUB_USERNAME }}
          password: ${{ secrets.ALIYUNHUB_TOKEN }}

      - name: Build and push
        run: |
          docker pull k8s.gcr.io/e2e-test-images/jessie-dnsutils:1.3
          docker tag k8s.gcr.io/e2e-test-images/jessie-dnsutils:1.3 registry-intl.cn-hangzhou.aliyuncs.com/deveops_k8s/jessie-dnsutils:1.3
          docker push registry-intl.cn-hangzhou.aliyuncs.com/deveops_k8s/jessie-dnsutils:1.3