name: mysql_8.0.28
on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/mysql_8.0.28.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2

      - name: Login in AliYun Registry
        uses: docker/login-action@v1
        with:
          registry: registry-intl.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUNHUB_USERNAME }}
          password: ${{ secrets.ALIYUNHUB_TOKEN }}

      - name: Build and push
        run: |
          docker pull mysql:8.0.28
          docker tag  mysql:8.0.28 registry-intl.cn-hangzhou.aliyuncs.com/fky357/mysql:8.0.28
          docker push registry-intl.cn-hangzhou.aliyuncs.com/fky357/mysql:8.0.28
