name: rancher-agent_2.8.2-multi-platform
on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/rancher-agent_2.8.2-multi-platform.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2

      - name: Login in AliYun Registry
        uses: docker/login-action@v1
        with:
          registry: registry-intl.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUNHUB_USERNAME }}
          password: ${{ secrets.ALIYUNHUB_TOKEN }}
          
      # 这个流程只复制了当前平台的子镜像（比如 amd64），
      # 推过去的 v2.8.2-multi 实际上不是 multi-arch 镜像。
      # 正确方式是用 `docker buildx imagetools create` 合并多个架构的镜像。
      #
      #- name: Build and push
      #  run: |
      #    docker manifest inspect rancher/rancher-agent@sha256:c200e336a23c8279e8748fb38d03bdb6d247b8561c4f1e09d8cf33bf6d495a51 | jq '.manifests[].platform'
      #    docker pull  rancher/rancher-agent@sha256:c200e336a23c8279e8748fb38d03bdb6d247b8561c4f1e09d8cf33bf6d495a51
      #    docker tag  rancher/rancher-agent@sha256:c200e336a23c8279e8748fb38d03bdb6d247b8561c4f1e09d8cf33bf6d495a51 registry-intl.cn-hangzhou.aliyuncs.com/fky357/rancher-agent:v2.8.2-multi
      #    docker push registry-intl.cn-hangzhou.aliyuncs.com/fky357/rancher-agent:v2.8.2-multi
          
      # GitHub Actions 中正确转存一个多架构（multi-arch）的镜像到阿里云容器镜像服务（ACR），
      # 不能简单地 docker pull + tag + push，否则只会推送当前 runner 架构（通常是 amd64）的那一个子镜像。
      - name: Mirror multi-arch image to Aliyun ACR
        run: |
          docker buildx create --name mirror-builder --use || docker buildx use mirror-builder      
          echo 'FROM rancher/rancher-agent@sha256:c200e336a23c8279e8748fb38d03bdb6d247b8561c4f1e09d8cf33bf6d495a51' > Dockerfile      
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --file Dockerfile \
            --tag registry-intl.cn-hangzhou.aliyuncs.com/fky357/rancher-agent:v2.8.2-multi \
            --push \
            .      
          docker buildx rm mirror-builder
      - name: Check pushed image platforms
        run: |
          docker manifest inspect registry-intl.cn-hangzhou.aliyuncs.com/fky357/rancher-agent:v2.8.2-multi | jq '.manifests[].platform'
