name: rancher-save-images-arm64

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/rancher-save-images-arm64.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/arm64,linux/amd64
          
      - name: Save Rancher images (arm64)
        run: |
          chmod +x rancher-save-images-v2.11.3-arm64.sh
          ./rancher-save-images-v2.11.3-arm64.sh --image-list rancher-images-v2.10.0-10.txt --images rancher-images-arm64.tar.gz --platform linux/arm64
          
      - name: Upload rancher-images-arm64.tar.gz
        uses: actions/upload-artifact@v4
        with:
          name: rancher-images-arm64
          path: rancher-images-arm64.tar.gz
