name: rancher-multi-platform
on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/rancher-multi-platform.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2

      - name: Login in AliYun Registry
        uses: docker/login-action@v1
        with:
          registry: registry-intl.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUNHUB_USERNAME }}
          password: ${{ secrets.ALIYUNHUB_TOKEN }}
          
      - name: Mirror multi-arch image to Aliyun ACR
        run: |
          docker buildx create --name multi-builder --use || docker buildx use multi-builder
          docker buildx imagetools create \
          --tag registry-intl.cn-hangzhou.aliyuncs.com/fky357/mirrored-coredns-coredns:1.12.0 \
          docker.io/rancher/mirrored-coredns-coredns:1.12.0
          
      # 用于验证推送的镜像是否支持 arm64
      - name: Check pushed image platforms
        run: |
          docker manifest inspect registry-intl.cn-hangzhou.aliyuncs.com/fky357/mirrored-coredns-coredns:1.12.0 | jq '.manifests[].platform'
