name: rancher-save-images
on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/rancher-save-images.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2
        
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Remove all Docker images
        run: |
          docker rmi -f $(docker images -q) || true 
          
      - name: Save Rancher images
        run: |
          chmod +x rancher-save-images-v2.11.3.sh
          ./rancher-save-images-v2.11.3.sh --image-list rancher-images-v2.10.0-02.txt      
          
      - name: Upload rancher-images.tar.gz
        uses: actions/upload-artifact@v4
        with:
          name: rancher-images
          path: rancher-images.tar.gz
